'''
Created on 2012-12-06

@author: Marty
'''

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
'''
import time

startTime = time.time()
a,b = 0,1
result = 0

while b < 4000000:
  # equivalent to b=a+b a=b
  a,b=b,a+b
  #add only even terms
  if b % 2 == 0:
    result += b
    
print result
print "Time Elapsed: " + str(time.time() - startTime)